### ISSUE TITLE
SD1.5をcolab環境下で動かすと以下のエラーが発生

### ISSUE THREAD

**Issue by renoro** [hnmr293/sd-webui-cutoff#29]
Warning: ControlNet failed to load SGM - will use LDM instead.
[Cutoff] failed to load `sgm.modules.GeneralConditioner`
*** Error loading script: cutoff.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-cutoff/scripts/cutoff.py", line 13, in <module>
        from scripts.cutofflib.embedding import CLIP, CLIP_SDXL, generate_prompts, token_to_block
      File "/content/stable-diffusion-webui/extensions/sd-webui-cutoff/scripts/cutofflib/embedding.py", line 15, in <module>
        class ClipWrapper:
      File "/content/stable-diffusion-webui/extensions/sd-webui-cutoff/scripts/cutofflib/embedding.py", line 16, in ClipWrapper
        def __init__(self, te: Union[CLIP,CLIP_SDXL]):
    NameError: name 'CLIP_SDXL' is not defined

このようなエラーが発生し、項目自体が表示されず利用が出来ないようです。

**Comment by hnmr293** [comment]
直ったと思います。
ダメだったら再オープンしてください。

**Comment by renoro** [comment]
> ダメだったら 再オープンしてください。

ありがとうございます。一応上記エラーは出なくなりましたが、今度は「[Cutoff] failed to load `sgm.modules.GeneralConditioner`」というエラー分が出ています。
しかし、一応起動した際にcut out多分は表示されています。
どのような影響を及ぼしているのかちょっと不明瞭な為報告させていただきます。

**Comment by hnmr293** [comment]
報告ありがとうございます。
そちらはSDXLバージョンのネットワークを読み込めなかったという報告です。WebUIのバージョンが古いと出ます。
ブラウザの方でエラーが出てなければ大丈夫です。
