### ISSUE TITLE
It is completely impossible to import from the forge environment

### ISSUE THREAD

**Issue by Karma3357** [hnmr293/sd-webui-cutoff#38]
*** Error loading script: [cutoff.py](https://unsafelink.com/http://cutoff.py)
    Traceback (most recent call last):
      File "D:\WEBUI\webui_forge_cu121_torch231\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\WEBUI\webui_forge_cu121_torch231\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\WEBUI\webui_forge_cu121_torch231\webui\extensions\sd-webui-cutoff\scripts\cutoff.py", line 12, in <module>
        from scripts.cutofflib.sdhook import SDHook
      File "D:\WEBUI\webui_forge_cu121_torch231\webui\extensions\sd-webui-cutoff\scripts\cutofflib\sdhook.py", line 7, in <module>
        from ldm.modules.diffusionmodules.openaimodel import (
    ModuleNotFoundError: No module named 'ldm'
    

I've been reinstalling cutoff over and over again to try and fix this issue, but I still haven't been able to do it. I couldn't find any information about it either, so I'm wondering if this extension is completely incompatible with forge, and if not, how to fix it.

**Comment by MartyDog1** [comment]
Same here. Same error.
